INSERT INTO School (school_name) VALUES
(N'Đại học Quốc gia Hà Nội'),
(N'Đại học Quốc gia TP.HCM'),
(N'Đại học Bách khoa Hà Nội'),
(N'Đại học Kinh tế Quốc dân'),
(N'Đại học Ngoại thương'),
(N'Đại học Y Hà Nội'),
(N'Đại học Xây dựng Hà Nội'),
(N'Đại học Bách khoa TP.HCM'),
(N'Đại học Khoa học Tự nhiên - ĐHQG HN'),
(N'Đại học Khoa học Xã hội và Nhân văn - ĐHQG HN'),
(N'Đại học Sư phạm Hà Nội'),
(N'Đại học Luật Hà Nội'),
(N'Đại học Kinh tế TP.HCM'),
(N'Đại học Tài chính - Marketing'),
(N'Đại học Thương mại'),
(N'Đại học Công nghiệp Hà Nội'),
(N'Đại học Công nghệ TP.HCM (HUTECH)'),
(N'Đại học Văn Lang'),
(N'Đại học Sài Gòn'),
(N'Đại học Hoa Sen'),
(N'Đại học Hàng hải Việt Nam'),
(N'Đại học Mỏ - Địa chất'),
(N'Đại học Giao thông Vận tải'),
(N'Đại học Sư phạm Kỹ thuật TP.HCM'),
(N'Đại học Nông Lâm TP.HCM'),
(N'Đại học Đà Nẵng'),
(N'Đại học Huế'),
(N'Đại học Tây Nguyên'),
(N'Đại học Cần Thơ'),
(N'Đại học Công nghiệp TP.HCM'),
(N'Đại học Kiến trúc Hà Nội'),
(N'Đại học Kiến trúc TP.HCM'),
(N'Đại học Tôn Đức Thắng'),
(N'Đại học Y Dược TP.HCM'),
(N'Đại học Sư phạm TP.HCM'),
(N'Đại học FPT'),
(N'Đại học Quốc tế RMIT Việt Nam'),
(N'Đại học Nguyễn Tất Thành'),
(N'Đại học Quốc tế Hồng Bàng'),
(N'Đại học Kinh tế - Luật - ĐHQG TP.HCM'),
(N'Đại học Kinh tế Đà Nẵng'),
(N'Đại học Đà Lạt'),
(N'Đại học Quy Nhơn'),
(N'Đại học Phan Thiết'),
(N'Đại học Lạc Hồng'),
(N'Đại học Đồng Nai'),
(N'Đại học Thủ Dầu Một'),
(N'Đại học Phạm Văn Đồng'),
(N'Đại học Quảng Nam'),
(N'Đại học Vinh'),
(N'Đại học Sư phạm Kỹ thuật Vinh'),
(N'Đại học Hồng Đức'),
(N'Đại học Nha Trang'),
(N'Đại học Khánh Hòa'),
(N'Đại học An Giang'),
(N'Đại học Cửu Long'),
(N'Đại học Tiền Giang'),
(N'Đại học Công nghiệp Vinh'),
(N'Đại học Kỹ thuật Y Dược Đà Nẵng'),
(N'Đại học Tây Đô'),
(N'Đại học Sư phạm Thể dục Thể thao TP.HCM'),
(N'Đại học Sư phạm Kỹ thuật Nam Định'),
(N'Đại học Y Thái Bình'),
(N'Đại học Hải Phòng'),
(N'Đại học Duy Tân'),
(N'Đại học Đông Á'),
(N'Đại học Văn Hiến'),
(N'Đại học Quốc tế Miền Đông'),
(N'Đại học Phú Xuân'),
(N'Đại học Trà Vinh'),
(N'Đại học Văn Lang'),
(N'Đại học Công nghiệp Quảng Ninh'),
(N'Đại học Kinh tế Nghệ An'),
(N'Đại học Bình Dương'),
(N'Đại học Y Dược Hải Phòng'),
(N'Đại học Quảng Bình'),
(N'Đại học Hà Tĩnh'),
(N'Đại học Nam Cần Thơ'),
(N'Đại học Sư phạm Nghệ thuật Trung ương'),
(N'Đại học Công nghệ Miền Đông'),
(N'Đại học Phenikaa'),
(N'Đại học Kinh doanh và Công nghệ Hà Nội'),
(N'Đại học FLC'),
(N'Đại học Quốc tế Bắc Hà'),
(N'Đại học Thăng Long'),
(N'Đại học Hòa Bình'),
(N'Đại học Đại Nam'),
(N'Đại học Việt Nhật'),
(N'Đại học Thái Bình'),
(N'Đại học Đông Đô'),
(N'Đại học Quốc tế Sài Gòn'),
(N'Đại học Thành Đô'),
(N'Đại học Hùng Vương'),
(N'Đại học Hoa Lư'),
(N'Đại học Khác');

INSERT INTO Company (company_name, description) VALUES
(N'FPT Software', N'Công ty phần mềm lớn nhất Việt Nam'),
(N'VNG Corporation', N'Công ty công nghệ và giải trí kỹ thuật số hàng đầu Việt Nam'),
(N'CMC Corporation', N'Tập đoàn công nghệ lớn tại Việt Nam, chuyên về giải pháp IT và dịch vụ phần mềm'),
(N'TMA Solutions', N'Công ty gia công phần mềm với quy mô quốc tế'),
(N'Viettel Digital', N'Tập đoàn viễn thông và công nghệ số lớn nhất Việt Nam'),
(N'VCCorp', N'Công ty công nghệ truyền thông và thương mại điện tử'),
(N'Haravan', N'Công ty cung cấp giải pháp thương mại điện tử cho doanh nghiệp'),
(N'Sendo', N'Sàn thương mại điện tử hàng đầu tại Việt Nam'),
(N'VNPT Technology', N'Công ty công nghệ thông tin và truyền thông thuộc Tập đoàn VNPT'),
(N'Rikkeisoft', N'Công ty phát triển phần mềm và dịch vụ công nghệ tại Việt Nam'),
(N'Axon Active Vietnam', N'Công ty phát triển phần mềm và dịch vụ IT quốc tế'),
(N'KMS Technology', N'Công ty công nghệ chuyên cung cấp dịch vụ phần mềm và giải pháp IT'),
(N'Bravebits', N'Công ty thiết kế website và giải pháp thương mại điện tử'),
(N'CreativeVietnam', N'Công ty chuyên về thiết kế web và phát triển thương mại điện tử'),
(N'Terasol', N'Công ty thiết kế website và ứng dụng di động'),
(N'CO-WELL Asia', N'Công ty phát triển phần mềm và giải pháp IT cho thị trường quốc tế'),
(N'Sutunam', N'Công ty thiết kế web và phát triển ứng dụng tại Việt Nam và Pháp'),
(N'CodeComplete', N'Công ty chuyên về phát triển phần mềm và thiết kế web'),
(N'TruongXuan Web', N'Công ty chuyên về dịch vụ thiết kế web và phát triển phần mềm'),
(N'PowerGate Software', N'Công ty phát triển phần mềm và công nghệ quốc tế'),
(N'Softek Vietnam', N'Công ty phát triển phần mềm, dịch vụ IT và thiết kế'),
(N'SmartOSC', N'Công ty thiết kế và phát triển các giải pháp thương mại điện tử'),
(N'MOR Software', N'Công ty phát triển phần mềm và cung cấp dịch vụ công nghệ'),
(N'Younet Media', N'Công ty công nghệ chuyên cung cấp giải pháp social media'),
(N'Orient Software', N'Công ty gia công phần mềm hàng đầu tại Việt Nam'),
(N'SVN Design', N'Công ty thiết kế đồ họa và phát triển ứng dụng'),
(N'DigiPencil MVV', N'Công ty sáng tạo và công nghệ hàng đầu Việt Nam'),
(N'Infinity Blockchain Labs', N'Công ty công nghệ blockchain và phát triển giải pháp IT'),
(N'BE Group', N'Công ty công nghệ với dịch vụ gọi xe BE và các giải pháp IT'),
(N'Momo', N'Công ty fintech cung cấp dịch vụ ví điện tử hàng đầu tại Việt Nam'),
(N'Viettel AI', N'Tập đoàn Viettel phát triển các giải pháp trí tuệ nhân tạo'),
(N'Công ty Khác', N'Công ty không có trong danh sách trên');

INSERT INTO Certification (certification_name) VALUES
(N'Chứng chỉ Lập trình Java'),
(N'Chứng chỉ Lập trình Python'),
(N'Chứng chỉ Lập trình Web'),
(N'Chứng chỉ Quản lý dự án'),
(N'Chứng chỉ Chuyên viên phân tích dữ liệu'),
(N'Chứng chỉ Tiếp thị kỹ thuật số'),
(N'Chứng chỉ SEO'),
(N'Chứng chỉ Quản trị mạng'),
(N'Chứng chỉ Thiết kế đồ họa'),
(N'Chứng chỉ Lãnh đạo'),
(N'Chứng chỉ Giao tiếp hiệu quả'),
(N'Chứng chỉ Dịch thuật'),
(N'Chứng chỉ Khai thác dữ liệu'),
(N'Chứng chỉ Kỹ thuật an ninh mạng'),
(N'Chứng chỉ Quản lý tài chính'),
(N'Chứng chỉ Kinh doanh quốc tế'),
(N'Chứng chỉ Nghiên cứu thị trường'),
(N'Chứng chỉ Quản lý chất lượng'),
(N'Chứng chỉ Tư vấn khách hàng'),
(N'Chứng chỉ Phát triển phần mềm'),
(N'Chứng chỉ Quản lý rủi ro'),
(N'Chứng chỉ IELTS'),
(N'Chứng chỉ TOEIC'),
(N'Chứng chỉ TOEFL'),
(N'Chứng chỉ HSK (Tiếng Trung)'),
(N'Chứng chỉ JLPT (Tiếng Nhật)'),
(N'Chứng chỉ DELF (Tiếng Pháp)'),
(N'Chứng chỉ tiếng Đức'),
(N'Chứng chỉ tiếng Hàn'),
(N'Chứng chỉ tiếng Tây Ban Nha'),
(N'Chứng chỉ tiếng Ý'),
(N'Chứng chỉ tiếng Bồ Đào Nha'),
(N'Chứng chỉ giao tiếp tiếng Anh'),
(N'Chứng chỉ khác về ngoại ngữ'),
(N'Chứng chỉ Khác');

INSERT INTO Skill (skill_name) VALUES
(N'Giao tiếp'),
(N'Làm việc nhóm'),
(N'Giải quyết vấn đề'),
(N'Lãnh đạo'),
(N'Quản lý thời gian'),
(N'Thích ứng'),
(N'Quản lý dự án'),
(N'Sáng tạo'),
(N'Tư duy phản biện'),
(N'Chăm sóc khách hàng'),
(N'Bán hàng'),
(N'Sử dụng Microsoft Office'),
(N'Phân tích dữ liệu'),
(N'Ngôn ngữ truy vấn SQL'),
(N'Lập trình Java'),
(N'Lập trình Python'),
(N'Lập trình web HTML/CSS'),
(N'Lập trình JavaScript'),
(N'Lập trình C++'),
(N'Kỹ năng mạng máy tính'),
(N'Tiếp thị kỹ thuật số'),
(N'Tối ưu hóa công cụ tìm kiếm SEO'),
(N'Thiết kế đồ họa'),
(N'Thiết kế giao diện và trải nghiệm người dùng'),
(N'Nói trước đám đông'),
(N'Ngoại ngữ'),
(N'Viết nội dung'),
(N'Đàm phán'),
(N'Phân tích tài chính'),
(N'Lập trình tổng quát'),
(N'Khác');
